In [41]:
import numpy as np;
import pandas as pd;

In [5]:
a = np.array([1,1,1]);
b = np.array([2,2,2]);
print(np.vstack((a,b)));
print(np.vstack((a,b)).shape)
print(np.vstack((a,b)).ndim)

[[1 1 1]
 [2 2 2]]
(2, 3)
2


In [6]:
print(np.hstack((a,b)))

[1 1 1 2 2 2]


In [7]:
print(np.hstack((a,b)).shape)

(6,)


In [9]:
print(np.matrix(a).T)

[[1]
 [1]
 [1]]


In [12]:
print(a[np.newaxis,:])
print(a[np.newaxis,:].shape)
print(a[np.newaxis,:].T)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]


In [13]:
print(a[:,np.newaxis])

[[1]
 [1]
 [1]]


In [20]:
a = np.matrix(np.array([1,1,1]))
b = np.matrix(np.array([2,2,2]))
print(np.concatenate((a,b), axis = 0))

[[1 1 1]
 [2 2 2]]


In [21]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
print(np.split(a, 2, axis = 1))
c = np.split(a,2,axis=1)
print(c[0])
print(type(c[0]))
print(type(c))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[[0 1]
 [4 5]
 [8 9]]
<class 'numpy.ndarray'>
<class 'list'>


In [31]:
a = np.arange(4)
b = a
c = a
d = b
print(a)

[0 1 2 3]


In [32]:
a[0] = 12
print(a)

[12  1  2  3]


In [36]:
print(b is a)
print(b)
print(c)
print(d)

True
[12  1  2  3]
[12  1  2  3]
[12  1  2  3]


In [39]:
b = a.copy()
print(b)
b[1] = 13
print(a)
print(b)

[12  1  2  3]
[12  1  2  3]
[12 13  2  3]


In [44]:
df = pd.DataFrame(a)
print(df)
print(df.values)

    0
0  12
1   1
2   2
3   3
[[12]
 [ 1]
 [ 2]
 [ 3]]
