In [2]:
import tensorflow as tf;
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;
%matplot inline

/Users/penpen926/Library/anaconda/anaconda3/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
UsageError: Line magic function `%matplot` not found.


In [5]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(type(array))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
print('number of dim', array.ndim);
print('shape: ',array.shape);
print('size: ',array.size);

number of dim 2
shape:  (2, 3)
size:  6


In [7]:
a = np.array([1,2,3]);
print(type(a))

<class 'numpy.ndarray'>


In [11]:
a = np.array([1,2,3],dtype=np.float32)
print(a.dtype)

float32


In [13]:
a = np.zeros((3,4));
print(a);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a = np.ones((3,5,5));
print(a);

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
a = np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
a = np.arange(1,13,2)
a = a.reshape(2,3)
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [51]:
a = np.linspace(2,20,20).reshape(2,2,5)
print(a)
print(a[0:1,1])

[[[ 2.          2.94736842  3.89473684  4.84210526  5.78947368]
  [ 6.73684211  7.68421053  8.63157895  9.57894737 10.52631579]]

 [[11.47368421 12.42105263 13.36842105 14.31578947 15.26315789]
  [16.21052632 17.15789474 18.10526316 19.05263158 20.        ]]]
[[ 6.73684211  7.68421053  8.63157895  9.57894737 10.52631579]]


In [23]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a * b)
print(a**2)

[ 2  6 12 20]
[ 1  4  9 16]


In [25]:
print(a>2)
print(a[a>2])

[False False  True  True]
[3 4]


In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
print(a)
print(b)
print(a*b)
print(np.transpose(a))
print(np.dot(np.transpose(a),b))

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[ 4 10 18]
 [28 40 54]]
[[1 4]
 [2 5]
 [3 6]]
[[32 37 42]
 [43 50 57]
 [54 63 72]]


In [34]:
print(np.transpose(a).dot(b))
print(a.dot(np.transpose(b)))

[[32 37 42]
 [43 50 57]
 [54 63 72]]
[[ 32  50]
 [ 77 122]]


In [35]:
a = np.random.random((2,4))
print(a)

[[0.26737905 0.28844887 0.82093671 0.84319254]
 [0.42104331 0.39187159 0.57252469 0.9262866 ]]


In [36]:
print(np.sum(a))

4.531683360004042


In [40]:
print(np.min(a, axis=1))

[0.26737905 0.39187159]


In [38]:
print(np.max(a))

0.9262865992994986


In [41]:
a = np.random.random((3,4))
print(a)

[[0.28900215 0.20687832 0.14049008 0.9637216 ]
 [0.24690433 0.16282087 0.43109994 0.86968909]
 [0.42818852 0.85399961 0.33402166 0.68464135]]


In [42]:
print(np.argmin(a))
print(np.argmax(a))

2
3


In [43]:
print(np.mean(a))

0.46762146096587237


In [44]:
print(np.median(a))

0.3811050900118398


In [45]:
print(a);

[[0.28900215 0.20687832 0.14049008 0.9637216 ]
 [0.24690433 0.16282087 0.43109994 0.86968909]
 [0.42818852 0.85399961 0.33402166 0.68464135]]


In [46]:
print(np.cumsum(a))

[0.28900215 0.49588047 0.63637055 1.60009216 1.84699649 2.00981736
 2.44091729 3.31060639 3.73879491 4.59279452 4.92681618 5.61145753]


In [50]:
print(np.nonzero(a))
b = np.nonzero(a)
print(type(b))
print(b[0][1])

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
<class 'tuple'>
0


In [52]:
print(np.sort(a))

[[[ 2.          2.94736842  3.89473684  4.84210526  5.78947368]
  [ 6.73684211  7.68421053  8.63157895  9.57894737 10.52631579]]

 [[11.47368421 12.42105263 13.36842105 14.31578947 15.26315789]
  [16.21052632 17.15789474 18.10526316 19.05263158 20.        ]]]


In [53]:
print(a.T)

[[[ 2.         11.47368421]
  [ 6.73684211 16.21052632]]

 [[ 2.94736842 12.42105263]
  [ 7.68421053 17.15789474]]

 [[ 3.89473684 13.36842105]
  [ 8.63157895 18.10526316]]

 [[ 4.84210526 14.31578947]
  [ 9.57894737 19.05263158]]

 [[ 5.78947368 15.26315789]
  [10.52631579 20.        ]]]


In [55]:
a = np.arange(5,20).reshape((3,5))
print(a)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [56]:
print(np.clip(a,10,14))

[[10 10 10 10 10]
 [10 11 12 13 14]
 [14 14 14 14 14]]


In [57]:
s = pd.Series([1,2,3,4.4,np.nan])
print(s)

0    1.0
1    2.0
2    3.0
3    4.4
4    NaN
dtype: float64


In [58]:
dates = pd.date_range('20181122',periods=6)
print(dates)

DatetimeIndex(['2018-11-22', '2018-11-23', '2018-11-24', '2018-11-25',
               '2018-11-26', '2018-11-27'],
              dtype='datetime64[ns]', freq='D')


In [61]:
df = pd.DataFrame(np.random.random((6,4)), index = dates, columns = ['a','b','c','d'])
print(df)

                   a         b         c         d
2018-11-22  0.406228  0.975858  0.467992  0.894185
2018-11-23  0.582743  0.974218  0.261332  0.631284
2018-11-24  0.809027  0.557844  0.481190  0.439199
2018-11-25  0.808508  0.390588  0.877262  0.713915
2018-11-26  0.563745  0.048512  0.847534  0.531647
2018-11-27  0.365884  0.075476  0.164038  0.155685


In [70]:
df = pd.DataFrame({'a': [123,234], 'b': [3.2,3.2], 'c': [4.5, 5.6], 'd':[6.4, 7.6]}, index = [1,2])
print(df)

     a    b    c    d
1  123  3.2  4.5  6.4
2  234  3.2  5.6  7.6


In [66]:
print(df.dtypes)

a      int64
b    float64
c    float64
d    float64
dtype: object


In [80]:
print(df.index)
print(df.index.values)
print(type(df.index))
print(type(df.index.values))
print(df.columns)
print(df.columns.values)
print(type(df.columns.values))
print(df.values)
print(type(df.values))

Int64Index([1, 2], dtype='int64')
[1 2]
<class 'pandas.core.indexes.numeric.Int64Index'>
<class 'numpy.ndarray'>
Index(['a', 'b', 'c', 'd'], dtype='object')
['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
[[123.    3.2   4.5   6.4]
 [234.    3.2   5.6   7.6]]
<class 'numpy.ndarray'>


In [82]:
df.describe()
print(df.T)

       1      2
a  123.0  234.0
b    3.2    3.2
c    4.5    5.6
d    6.4    7.6


In [92]:
df = pd.DataFrame([[6,7],[4,5],[2,1]], index =[1,2,3])
print(df)
df = df.sort_values(axis=0,by=0)
print(df)

   0  1
1  6  7
2  4  5
3  2  1
   0  1
3  2  1
2  4  5
1  6  7


In [94]:
dates = pd.date_range('20181112',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)), index = dates, columns = ['A','B','C','D']);
print(df)


             A   B   C   D
2018-11-12   0   1   2   3
2018-11-13   4   5   6   7
2018-11-14   8   9  10  11
2018-11-15  12  13  14  15
2018-11-16  16  17  18  19
2018-11-17  20  21  22  23


In [97]:
print(df['A'])
print(df.A)
print(df.A.values)

2018-11-12     0
2018-11-13     4
2018-11-14     8
2018-11-15    12
2018-11-16    16
2018-11-17    20
Freq: D, Name: A, dtype: int64
2018-11-12     0
2018-11-13     4
2018-11-14     8
2018-11-15    12
2018-11-16    16
2018-11-17    20
Freq: D, Name: A, dtype: int64
[ 0  4  8 12 16 20]


In [104]:
print(type(df.A))
print(df[0:3])
print(type(df[0:3]))
print(df.loc['20181114'])
print(type(df.loc['20181114']))
print(df.loc[:,['A','B']])

<class 'pandas.core.series.Series'>
            A  B   C   D
2018-11-12  0  1   2   3
2018-11-13  4  5   6   7
2018-11-14  8  9  10  11
<class 'pandas.core.frame.DataFrame'>
A     8
B     9
C    10
D    11
Name: 2018-11-14 00:00:00, dtype: int64
<class 'pandas.core.series.Series'>
             A   B
2018-11-12   0   1
2018-11-13   4   5
2018-11-14   8   9
2018-11-15  12  13
2018-11-16  16  17
2018-11-17  20  21


In [109]:
print(df.iloc[1:3,1:4])
print(type(df.iloc[1:3,1:4]))
print(df.values[1:3,1:4])

            B   C   D
2018-11-13  5   6   7
2018-11-14  9  10  11
<class 'pandas.core.frame.DataFrame'>
[[ 5  6  7]
 [ 9 10 11]]


In [111]:
df.iloc[2,3] = 111
print(df)

             A   B   C    D
2018-11-12   0   1   2    3
2018-11-13   4   5   6    7
2018-11-14   8   9  10  111
2018-11-15  12  13  14   15
2018-11-16  16  17  18   19
2018-11-17  20  21  22   23
