In [4]:
import tensorflow as tf;
import numpy as np;
import matplotlib.pyplot as plt;

sess = tf.InteractiveSession();
zero_tensor = tf.zeros(shape = (2,3));
print(zero_tensor.eval());

Tensor("zeros_2:0", shape=(2, 3), dtype=float32)


/Users/penpen926/Library/anaconda/anaconda3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
x = [[1,2,3,],[4,5,6]];
tensor_1= tf.Variable(initial_value = x);
tensor_2 = tf.zeros(shape = tensor_1.shape);
print(tensor_2.eval());

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
x = tf.convert_to_tensor((np.array([[1,2,3],[4,5,6]])));
x_tensor= tf.zeros_like(x);
print(x_tensor.eval());

[[0 0 0]
 [0 0 0]]


In [8]:
x_array = np.ones(shape = (3,2),dtype = np.int8);
x_array.fill(5);
print(x_array);
x_tensor = tf.convert_to_tensor(x_array);
print(x_tensor.eval());

[[5 5]
 [5 5]
 [5 5]]
[[5 5]
 [5 5]
 [5 5]]


In [9]:
x_array = np.array([[1,3,5],[4,6,8]]);
x_tensor = tf.convert_to_tensor(x_array);
x_tensor_2 = 
print(x_tensor.eval());

[[1 3 5]
 [4 6 8]]


In [13]:
x_tensor = tf.fill(dims = [2,3],value = 4)
print(x_tensor.eval());
x_tensor= tf.constant(4, shape=[2,3]);
print(x_tensor.eval());

[[4 4 4]
 [4 4 4]]
[[4 4 4]
 [4 4 4]]


In [16]:
x_tensor = tf.linspace(start = 5.0, stop= 10.0, num = 50 );
print(x_tensor.eval());

[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ]


In [17]:
x_tensor = tf.range(start = 10, limit = 102, delta = 2);
print(x_tensor.eval());

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


In [18]:
x_tensor = tf.random_normal(shape = [3,2], mean = 0.0, stddev = 2.0);
print(x_tensor.eval());

[[-1.5540721   0.6751405 ]
 [ 0.09201242  1.3693898 ]
 [ 0.98006546  2.6186945 ]]


In [20]:
x_tensor = tf.random_uniform(shape = [3,2], minval = 0.0, maxval =2.0);
print(x_tensor.eval());

[[0.9475851  0.4745946 ]
 [1.3575041  1.1014714 ]
 [0.04827428 0.89519954]]
