In [3]:
import tensorflow as tf;
import numpy as np;
import matplotlib.pyplot as plt;

sess = tf.InteractiveSession();
zero_tensor = tf.zeros(shape = (2,3));
print(zero_tensor.eval());

[[0. 0. 0.]
 [0. 0. 0.]]


C:\softwares\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [2]:
x = [[1,2,3,],[4,5,6]];
tensor_1= tf.Variable(initial_value = x);
tensor_2 = tf.zeros(shape = tensor_1.shape);
print(tensor_2.eval());

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
x = tf.convert_to_tensor((np.array([[1,2,3],[4,5,6]])));
x_tensor= tf.zeros_like(x);
print(x_tensor.eval());

[[0 0 0]
 [0 0 0]]


In [4]:
x_array = np.ones(shape = (3,2),dtype = np.int8);
x_array.fill(5);
print(x_array);
x_tensor = tf.convert_to_tensor(x_array);
print(x_tensor.eval());

[[5 5]
 [5 5]
 [5 5]]
[[5 5]
 [5 5]
 [5 5]]


In [5]:
x_array = np.array([[1,3,5],[4,6,8]]);
x_tensor = tf.convert_to_tensor(x_array);
x_tensor_2 = 
print(x_tensor.eval());

SyntaxError: invalid syntax (<ipython-input-5-38173867843b>, line 3)

In [ ]:
x_tensor = tf.fill(dims = [2,3],value = 4)
print(x_tensor.eval());
x_tensor= tf.constant(4, shape=[2,3]);
print(x_tensor.eval());

In [ ]:
x_tensor = tf.linspace(start = 5.0, stop= 10.0, num = 50 );
print(x_tensor.eval());

In [ ]:
x_tensor = tf.range(start = 10, limit = 102, delta = 2);
print(x_tensor.eval());

In [18]:
x_tensor = tf.random_normal(shape = [3,2], mean = 0.0, stddev = 2.0);
print(x_tensor.eval());

[[-1.5540721   0.6751405 ]
 [ 0.09201242  1.3693898 ]
 [ 0.98006546  2.6186945 ]]


In [20]:
x_tensor = tf.random_uniform(shape = [3,2], minval = 0.0, maxval =2.0);
print(x_tensor.eval());

[[0.9475851  0.4745946 ]
 [1.3575041  1.1014714 ]
 [0.04827428 0.89519954]]


In [4]:
import tensorflow as tf;
import numpy as np;
sess = tf.InteractiveSession();
x_tensor = tf.constant(value = [[1,2],[3,4],[5,6]])
x_tensor_reshuffled = tf.random_shuffle(value = x_tensor);
print(x_tensor_reshuffled.eval());

[[3 4]
 [5 6]
 [1 2]]


In [7]:
x = tf.random_normal([10,10,3]);
out = tf.random_crop(x,[5,5,3])
print(out.eval());

[[[ 0.25570485  0.8702508   0.611745  ]
  [ 1.2262843  -1.6900889   0.1969779 ]
  [-0.76532966  0.18363473 -0.73740023]
  [-0.48231933  0.7553582   0.42580855]
  [-1.7409163   1.0080432   0.32623106]]

 [[-0.65734303  1.2046068   0.40413538]
  [ 0.6593236  -0.2504608   2.3852382 ]
  [ 0.7516138  -0.3755561  -0.03367322]
  [-0.05383167  0.06148516 -0.57265246]
  [-0.45422488 -0.1694904  -2.8577235 ]]

 [[ 0.25004187 -1.17298    -1.4566654 ]
  [-1.9505424  -0.36227345 -0.01011753]
  [ 0.86284435  1.1450217   0.4118414 ]
  [-1.125876   -1.2525573  -0.73209685]
  [ 0.5895926   0.9959986  -0.6524282 ]]

 [[ 0.38335413 -0.01821681 -0.37893742]
  [-0.3056471  -0.2380733   0.73320633]
  [-1.1362953  -1.1622163  -0.5225456 ]
  [ 0.8448778  -0.3178058  -1.5457073 ]
  [ 0.7454955   0.10206129  0.25640756]]

 [[ 1.3584608  -1.3926457   1.5787004 ]
  [-0.71701354 -0.831214    0.6608228 ]
  [-0.36379746  0.70694023 -2.451692  ]
  [-0.4593825   0.85331976  0.8864741 ]
  [ 0.97816616  2.270493   -0.86

In [9]:
from scipy import misc;
import matplotlib.pyplot as plt;
img = misc.imread('cat.png');
im = tf.Variable(img);
im_ = tf.random_crop(im, [100,100,3]);
init = tf.global_variables_initializer();
sess.run(init);
ims = im.eval();
ims_ = im_.eval();
plt.subplot(1,2,1);
plt.imshow(ims);
plt.subplot(1,2,2);
plt.imshow(ims_);
plt.show();

ValueError: Operation 'init' has been marked as not fetchable.

In [8]:
x=  tf.random_normal(shape = [])
y = tf.random_normal(shape = []);
print(x.eval());
print(y.eval());
z = tf.cond(pred = x>y, true_fn = lambda: tf.add(x,y), false_fn = lambda: tf.subtract(x,y));
print(z.eval());

ValueError: Operation 'random_normal_4' has been marked as not fetchable.